export const mockUsers = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    nationality: "United States",
    joinDate: "2024-01-15",
    totalBookings: 5,
    totalSpent: 1247,
    preferences: ["K-pop", "Food", "Culture", "Shopping"],
    emergencyContact: {
      name: "Jane Doe",
      phone: "+1 (555) 987-6543",
      relationship: "Sister",
    },
  },
]

export const mockBookings = [
  {
    id: "BK001",
    userId: "1",
    type: "sim-card",
    title: "SIM Card - Tourist Plan",
    description: "7 days unlimited data + 100 min calls",
    price: 25.0,
    status: "confirmed",
    bookingDate: "2024-03-10",
    serviceDate: "2024-03-15",
    location: "Incheon Airport (ICN)",
    qrCode: "QR123456789",
    provider: "KT Telecom",
    details: {
      plan: "Tourist 7-Day",
      data: "Unlimited",
      calls: "100 minutes",
      pickup: "Terminal 1, Arrival Hall B",
    },
  },
  {
    id: "BK002",
    userId: "1",
    type: "experience",
    title: "K-Pop Dance Class",
    description: "Learn choreography from your favorite K-pop songs",
    price: 45.0,
    status: "upcoming",
    bookingDate: "2024-03-12",
    serviceDate: "2024-03-17T14:00:00",
    location: "Hongdae, Seoul",
    instructor: "Min-ji Park",
    details: {
      duration: "2 hours",
      maxParticipants: 12,
      difficulty: "Beginner",
      address: "123 Hongik-ro, Mapo-gu, Seoul",
    },
  },
  {
    id: "BK003",
    userId: "1",
    type: "tour",
    title: "Street Food Tour",
    description: "Taste authentic Korean street food with a local guide",
    price: 75.0,
    status: "pending",
    bookingDate: "2024-03-13",
    serviceDate: "2024-03-19T18:00:00",
    location: "Myeongdong, Seoul",
    guide: "Chef Kim",
    details: {
      duration: "3 hours",
      maxParticipants: 8,
      includes: "Food tastings, drinks, guide",
      meetingPoint: "Myeongdong Station Exit 6",
    },
  },
]

export const mockExperiences = [
  {
    id: "EXP001",
    title: "K-Pop Dance Class",
    category: "kpop",
    description: "Learn choreography from your favorite K-pop songs",
    price: 45,
    duration: "2 hours",
    maxParticipants: 12,
    rating: 4.9,
    reviewCount: 234,
    location: "Hongdae, Seoul",
    image: "from-purple-500 to-pink-500",
    badge: "Popular",
    instructor: "Min-ji Park",
    includes: ["Professional instruction", "Practice video", "Certificate"],
    schedule: ["10:00 AM", "2:00 PM", "6:00 PM"],
    difficulty: "Beginner",
  },
  {
    id: "EXP002",
    title: "K-Pop Studio Tour",
    category: "kpop",
    description: "Visit real recording studios and entertainment companies",
    price: 65,
    duration: "3 hours",
    maxParticipants: 15,
    rating: 4.8,
    reviewCount: 189,
    location: "Gangnam, Seoul",
    image: "from-blue-500 to-purple-500",
    badge: "New",
    includes: ["Studio visits", "Meet industry professionals", "Photo opportunities"],
    schedule: ["9:00 AM", "1:00 PM"],
    difficulty: "All levels",
  },
  {
    id: "EXP003",
    title: "Hanbok Experience",
    category: "culture",
    description: "Dress in traditional Korean clothing and explore palaces",
    price: 55,
    duration: "4 hours",
    maxParticipants: 8,
    rating: 4.9,
    reviewCount: 156,
    location: "Bukchon Hanok Village",
    image: "from-green-500 to-blue-500",
    badge: "Traditional",
    includes: ["Hanbok rental", "Hair styling", "Professional photos", "Palace entry"],
    schedule: ["9:00 AM", "1:00 PM"],
    difficulty: "All levels",
  },
  {
    id: "EXP004",
    title: "Street Food Tour",
    category: "food",
    description: "Taste authentic Korean street food with a local guide",
    price: 75,
    duration: "3 hours",
    maxParticipants: 8,
    rating: 4.9,
    reviewCount: 298,
    location: "Myeongdong & Dongdaemun",
    image: "from-red-500 to-orange-500",
    badge: "Bestseller",
    includes: ["10+ food tastings", "Local guide", "Drinks", "Cultural insights"],
    schedule: ["11:00 AM", "3:00 PM", "6:00 PM"],
    difficulty: "All levels",
  },
  {
    id: "EXP005",
    title: "Korean Cooking Class",
    category: "food",
    description: "Learn to cook traditional Korean dishes",
    price: 60,
    duration: "3 hours",
    maxParticipants: 10,
    rating: 4.7,
    reviewCount: 167,
    location: "Hongdae",
    image: "from-yellow-500 to-orange-500",
    includes: ["Ingredients", "Recipe cards", "Meal", "Apron"],
    schedule: ["10:00 AM", "2:00 PM"],
    difficulty: "Beginner",
  },
  {
    id: "EXP006",
    title: "Jeju Island Hiking",
    category: "nature",
    description: "Hike Hallasan mountain and explore volcanic landscapes",
    price: 95,
    duration: "Full day",
    maxParticipants: 12,
    rating: 4.8,
    reviewCount: 89,
    location: "Jeju Island",
    image: "from-green-600 to-blue-600",
    badge: "Adventure",
    includes: ["Transportation", "Guide", "Lunch", "Equipment"],
    schedule: ["7:00 AM"],
    difficulty: "Intermediate",
  },
]

export const mockCommunityPosts = [
  {
    id: "POST001",
    author: {
      name: "Sarah Johnson",
      avatar: "/placeholder.svg?height=40&width=40",
      badge: "Verified Traveler",
      location: "First-time visitor from USA",
    },
    timestamp: "2 hours ago",
    type: "question",
    tags: ["Question", "Seoul"],
    title: "Best areas to stay in Seoul for first-time visitors?",
    content:
      "I'm planning my first trip to Seoul next month and wondering about the best neighborhoods to stay in. I'm interested in being close to tourist attractions, good food, and easy transportation. Any recommendations?",
    likes: 24,
    replies: 12,
    hasLiked: false,
  },
  {
    id: "POST002",
    author: {
      name: "Min-jun Kim",
      avatar: "/placeholder.svg?height=40&width=40",
      badge: "Local Expert",
      location: "Seoul Local Guide",
    },
    timestamp: "4 hours ago",
    type: "tip",
    tags: ["Tip", "Food", "Budget"],
    title: "Hidden gem: Best Korean BBQ under $15 per person",
    content:
      "Found this amazing local BBQ place in Hongdae that most tourists don't know about. Incredible quality meat, unlimited banchan, and the owner speaks English! Perfect for budget travelers who want authentic Korean BBQ experience.",
    details: {
      location: "123 Hongik-ro, Mapo-gu",
      hours: "5 PM - 2 AM daily",
      price: "₩12,000-15,000 per person",
    },
    likes: 67,
    replies: 23,
    hasLiked: true,
  },
  {
    id: "POST003",
    author: {
      name: "Anna Lopez",
      avatar: "/placeholder.svg?height=40&width=40",
      badge: "Frequent Visitor",
      location: "K-pop enthusiast from Spain",
    },
    timestamp: "6 hours ago",
    type: "experience",
    tags: ["Experience", "K-pop", "Concert"],
    title: "Just attended my first K-pop concert in Seoul! 🎤",
    content:
      "What an incredible experience! The energy was absolutely amazing. For anyone planning to attend concerts, here are some tips: arrive early for merchandise, bring a portable charger, and learn some fan chants beforehand. The Korean fans were so welcoming and helped me with everything!",
    likes: 89,
    replies: 31,
    hasLiked: false,
  },
]

export const mockServices = [
  {
    id: "SRV001",
    type: "currency",
    title: "Currency Exchange",
    description: "Get the best exchange rates with instant quotes",
    rates: {
      USD: { rate: 1320, fee: 0.5 },
      EUR: { rate: 1450, fee: 0.5 },
      JPY: { rate: 9.8, fee: 0.5 },
      CNY: { rate: 185, fee: 0.5 },
    },
    locations: ["Incheon Airport", "Myeongdong", "Gangnam", "Hongdae"],
  },
  {
    id: "SRV002",
    type: "sim",
    title: "SIM Cards",
    description: "Stay connected with high-speed data plans",
    plans: [
      {
        id: "SIM001",
        name: "Tourist Plan - 7 Days",
        price: 25,
        data: "Unlimited",
        calls: "100 min",
        validity: "7 days",
      },
      {
        id: "SIM002",
        name: "Extended Stay - 30 Days",
        price: 65,
        data: "Unlimited",
        calls: "300 min",
        validity: "30 days",
      },
      {
        id: "SIM003",
        name: "Data Only - 14 Days",
        price: 35,
        data: "50GB",
        calls: "None",
        validity: "14 days",
      },
    ],
    pickupLocations: ["Incheon Airport (ICN)", "Gimpo Airport (GMP)", "Seoul Station", "Myeongdong Tourist Info"],
  },
  {
    id: "SRV003",
    type: "transport",
    title: "Transportation",
    description: "Book trains, subway passes, and transfers",
    options: [
      {
        type: "ktx",
        name: "KTX High-Speed Rail",
        routes: ["Seoul-Busan", "Seoul-Daegu", "Seoul-Gwangju"],
        price: "From ₩59,800",
      },
      {
        type: "subway",
        name: "T-money Card",
        options: ["1-Day Pass - $5", "7-Day Pass - $25"],
        coverage: "Seoul Metro & Bus",
      },
      {
        type: "transfer",
        name: "Airport Transfer",
        options: ["Private car", "Shared shuttle", "Express train"],
        price: "From $15",
      },
    ],
  },
]

export const mockItinerary = [
  {
    day: 1,
    date: "2024-03-15",
    title: "Arrival & First Impressions",
    activities: [
      {
        time: "10:00",
        title: "Arrive at ICN Airport",
        type: "transport",
        status: "completed",
        notes: "Flight KE123 - Pick up SIM card at Terminal 1",
      },
      {
        time: "12:00",
        title: "Check into Hotel",
        type: "accommodation",
        status: "completed",
        location: "Myeongdong",
        notes: "Lotte Hotel Seoul - Room 1205",
      },
      {
        time: "15:00",
        title: "Explore Myeongdong",
        type: "sightseeing",
        status: "completed",
        notes: "Shopping street, street food, cosmetics",
      },
      {
        time: "18:00",
        title: "Korean BBQ Dinner",
        type: "dining",
        status: "completed",
        location: "Maple Tree House",
        notes: "First Korean BBQ experience!",
      },
    ],
  },
  {
    day: 2,
    date: "2024-03-16",
    title: "Historical Seoul",
    activities: [
      {
        time: "09:00",
        title: "Gyeongbokgung Palace",
        type: "sightseeing",
        status: "completed",
        notes: "Changing of the guard ceremony at 10:00",
      },
      {
        time: "12:00",
        title: "Bukchon Hanok Village",
        type: "sightseeing",
        status: "completed",
        notes: "Traditional architecture, photo spots",
      },
      {
        time: "15:00",
        title: "Insadong Shopping",
        type: "shopping",
        status: "completed",
        notes: "Traditional crafts, tea houses",
      },
      {
        time: "18:00",
        title: "Traditional Korean Dinner",
        type: "dining",
        status: "completed",
        location: "Sanchon Temple Food",
      },
    ],
  },
  {
    day: 3,
    date: "2024-03-17",
    title: "K-Pop & Modern Culture",
    activities: [
      {
        time: "10:00",
        title: "Gangnam District Tour",
        type: "sightseeing",
        status: "upcoming",
        notes: "Gangnam Style statue, COEX Mall",
      },
      {
        time: "14:00",
        title: "K-Pop Dance Class",
        type: "experience",
        status: "booked",
        location: "Hongdae",
        bookingId: "BK002",
      },
      {
        time: "17:00",
        title: "Hongdae Exploration",
        type: "sightseeing",
        status: "planned",
        notes: "University area, street performances",
      },
      {
        time: "20:00",
        title: "Hongdae Nightlife",
        type: "entertainment",
        status: "planned",
        notes: "Clubs, karaoke, late-night food",
      },
    ],
  },
]

export const mockReviews = [
  {
    id: "REV001",
    experienceId: "EXP001",
    userId: "1",
    userName: "John Doe",
    userAvatar: "/placeholder.svg?height=32&width=32",
    rating: 5,
    title: "Amazing K-Pop Experience!",
    content:
      "The K-Pop dance class was absolutely incredible! Min-ji was such a patient and talented instructor. I learned the choreography to my favorite BTS song and even got a certificate. The studio was professional and the other participants were so friendly. Definitely a must-do for any K-pop fan visiting Seoul!",
    date: "2024-03-18",
    helpful: 23,
    verified: true,
    photos: ["photo1.jpg", "photo2.jpg"],
  },
  {
    id: "REV002",
    experienceId: "EXP004",
    userId: "2",
    userName: "Emma Wilson",
    userAvatar: "/placeholder.svg?height=32&width=32",
    rating: 5,
    title: "Best Food Tour Ever!",
    content:
      "Chef Kim was an amazing guide who took us to places I never would have found on my own. We tried over 10 different street foods, learned about Korean culture, and made new friends. The tteokbokki and hotteok were my favorites! Great value for money and perfect for food lovers.",
    date: "2024-03-16",
    helpful: 18,
    verified: true,
  },
  {
    id: "REV003",
    experienceId: "EXP003",
    userId: "3",
    userName: "Maria Garcia",
    userAvatar: "/placeholder.svg?height=32&width=32",
    rating: 4,
    title: "Beautiful Cultural Experience",
    content:
      "The hanbok experience was lovely! The staff helped me choose a beautiful hanbok and did my hair in a traditional style. Walking through Bukchon Hanok Village in traditional dress felt magical. The photos turned out amazing. Only minor issue was the wait time, but overall highly recommended!",
    date: "2024-03-14",
    helpful: 12,
    verified: true,
  },
]

export const mockNotifications = [
  {
    id: "NOT001",
    type: "booking",
    title: "Booking Confirmed",
    message: "Your K-Pop Dance Class booking has been confirmed for March 17, 2:00 PM",
    timestamp: "2024-03-12T10:30:00",
    read: false,
    actionUrl: "/dashboard?tab=bookings",
  },
  {
    id: "NOT002",
    type: "reminder",
    title: "Upcoming Experience",
    message: "Don't forget your K-Pop Dance Class tomorrow at 2:00 PM in Hongdae",
    timestamp: "2024-03-16T18:00:00",
    read: false,
    actionUrl: "/dashboard?tab=itinerary",
  },
  {
    id: "NOT003",
    type: "community",
    title: "New Reply",
    message: "Min-jun Kim replied to your question about Seoul neighborhoods",
    timestamp: "2024-03-15T14:20:00",
    read: true,
    actionUrl: "/community",
  },
]

export const mockWeather = {
  current: {
    temperature: 18,
    condition: "Partly Cloudy",
    humidity: 65,
    windSpeed: 12,
  },
  forecast: [
    { date: "2024-03-15", high: 20, low: 12, condition: "Sunny" },
    { date: "2024-03-16", high: 18, low: 10, condition: "Cloudy" },
    { date: "2024-03-17", high: 22, low: 14, condition: "Partly Cloudy" },
    { date: "2024-03-18", high: 19, low: 11, condition: "Rain" },
    { date: "2024-03-19", high: 21, low: 13, condition: "Sunny" },
  ],
}

export const mockEmergencyContacts = [
  {
    service: "Emergency Services",
    number: "119",
    description: "Fire, Ambulance, Rescue",
  },
  {
    service: "Police",
    number: "112",
    description: "Police Emergency",
  },
  {
    service: "Tourist Hotline",
    number: "1330",
    description: "24/7 Tourist Information & Assistance",
  },
  {
    service: "Medical Emergency",
    number: "1339",
    description: "Medical Emergency Information",
  },
  {
    service: "KoreaTravelHub Emergency",
    number: "+82-2-1234-5678",
    description: "24/7 Customer Support",
  },
]
